name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version from file
        run: |
          VERSION_FILE="$/jax_enums/_version.py"
          JAX_ENUMS_VERSION="$(cat jax_enums/_version.py | grep '__version__ = ' |  cut -d'=' -f2 | sed 's,\",,g' | sed "s,\',,g" | sed 's, ,,g')"
          echo "Current version is:"
          echo "$JAX_ENUMS_VERSION"

          echo "JAX_ENUMS_VERSION=$JAX_ENUMS_VERSION" >> $GITHUB_ENV

      - name: Create changelog and push tag
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: false
          fallback-version: ${{ env.JAX_ENUMS_VERSION }}
          skip-commit: true

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.JAX_ENUMS_VERSION }}
          name: "JAX_ENUMS release v${{ env.JAX_ENUMS_VERSION }}"
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pypa/build
        run: |
          python -m pip install build

      - name: Build wheel and sdist
        run: |
          python -m build --sdist --wheel --outdir dist/ .

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          password: ${{ secrets.PYPI_API_KEY }}
